### ISSUE TITLE
FIRST PASS - HTS.01 HTS Modality - slight discrepancy in Facility Index total tested

### ISSUE THREAD

**Issue by cwahle** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#59]
Slight difference in Facility HTS_TST for FY19Q1 (prior quarters, community and % positives all OK)
South Africa: OHA DB 9808 vs Pano 9840 
Kenya: OHA DB 77994 vs Pano 77997 
Central Asia: OHA DB 271 vs Pano 273
Eswatini: OHA DB 4928 vs Pano 4952
Ghana, Angola: OK

**Comment by jrose202** [comment]
seeing same issues - very slight differences.  I tried various filters to see if I could get the values to change and nothing works.

**Comment by noahbartlett** [comment]
I solved the issue. 

The problem is that the indicator (HTS_TST_POS) is not identical to (HTS_TST with a disaggregate of "Positive"). It is the same case for negatives. They should be identical and always used to be. The discrepancy between those two numbers is what is causing the issue you see above. 

For consistency's sake, I will use (HTS_TST) as a denominator for calculating yield rather than (HTS_TST_POS + HTS_TST_NEG).
